{
  "openapi": "3.0.0",
  "info": {
    "title": "Chat_API",
    "contact": {},
    "description": "The Best Chat on Vanguard",
    "version": "1.0"
  },
  "paths": {
    "/api/v1/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Register",
        "operationId": "Register",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/RegisterRequest"
                  },
                  {
                    "example": {
                      "firstname": "Freddy",
                      "lastname": "Zambrano",
                      "email": "freddy.zambrano.astorga@gmail.com",
                      "password": "FreddZam123%"
                    }
                  }
                ]
              },
              "example": {
                "firstname": "Freddy",
                "lastname": "Zambrano",
                "email": "freddy.zambrano.astorga@gmail.com",
                "password": "FreddZam123%"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get All Users",
        "operationId": "GetAllUsers",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/users/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Login User",
        "operationId": "LoginUser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/LoginUserRequest"
                  },
                  {
                    "example": {
                      "email": "freddy.zambrano.astorga@gmail.com",
                      "password": "FreddZam123%"
                    }
                  }
                ]
              },
              "example": {
                "email": "freddy.zambrano.astorga@gmail.com",
                "password": "FreddZam123%"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/conversations": {
      "post": {
        "tags": [
          "Conversations"
        ],
        "summary": "Create Conversation",
        "operationId": "CreateConversation",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateConversationRequest"
                  },
                  {
                    "example": {
                      "userId": 52,
                      "participantId": 52
                    }
                  }
                ]
              },
              "example": {
                "userId": 52,
                "participantId": 52
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/conversations/group": {
      "post": {
        "tags": [
          "Conversations"
        ],
        "summary": "Conversation Group",
        "operationId": "ConversationGroup",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/ConversationGroupRequest"
                  },
                  {
                    "example": {
                      "userId": 1,
                      "participantsIds": [
                        3,
                        4,
                        5
                      ],
                      "title": "chatNode"
                    }
                  }
                ]
              },
              "example": {
                "userId": 1,
                "participantsIds": [
                  3,
                  4,
                  5
                ],
                "title": "chatNode"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/conversations/{id}": {
      "get": {
        "tags": [
          "Conversations"
        ],
        "summary": "Get All Conversations By User",
        "operationId": "GetAllConversationsByUser",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 52
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/messages/conversation/{id}": {
      "post": {
        "tags": [
          "Messages"
        ],
        "summary": "Get Conversation",
        "operationId": "GetConversation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 7
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/GetConversationRequest"
                  },
                  {
                    "example": {
                      "content": "como estan?",
                      "senderId": 5
                    }
                  }
                ]
              },
              "example": {
                "content": "como estan?",
                "senderId": 5
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "tags": [
          "Messages"
        ],
        "summary": "Get Conversation Message",
        "operationId": "GetConversationMessage",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "RegisterRequest": {
        "title": "RegisterRequest",
        "required": [
          "firstname",
          "lastname",
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "firstname": "Freddy",
          "lastname": "Zambrano",
          "email": "freddy.zambrano.astorga@gmail.com",
          "password": "FreddZam123%"
        }
      },
      "LoginUserRequest": {
        "title": "LoginUserRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "freddy.zambrano.astorga@gmail.com",
          "password": "FreddZam123%"
        }
      },
      "CreateConversationRequest": {
        "title": "CreateConversationRequest",
        "required": [
          "userId",
          "participantId"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "format": "int32"
          },
          "participantId": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "userId": 52,
          "participantId": 52
        }
      },
      "ConversationGroupRequest": {
        "title": "ConversationGroupRequest",
        "required": [
          "userId",
          "participantsIds",
          "title"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "format": "int32"
          },
          "participantsIds": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            },
            "description": ""
          },
          "title": {
            "type": "string"
          }
        },
        "example": {
          "userId": 1,
          "participantsIds": [
            3,
            4,
            5
          ],
          "title": "chatNode"
        }
      },
      "GetConversationRequest": {
        "title": "GetConversationRequest",
        "required": [
          "content",
          "senderId"
        ],
        "type": "object",
        "properties": {
          "content": {
            "type": "string"
          },
          "senderId": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "content": "como estan?",
          "senderId": 5
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Users"
    },
    {
      "name": "Conversations"
    },
    {
      "name": "Messages"
    }
  ]
}